"""Phase 1.1.6 — the license and availability audit.

Walks the dataset registry, re-probes what can be re-probed, and writes
`reports/license_audit.md`: for every source, what license governs it, whether the raw files
may leave this machine, and whether it is still obtainable.

The audit is the gate the rest of the project depends on: **a dataset whose redistribution
status is unknown is treated as "no"**, and anything derived from it is checked against that
before publication.

    python -m src.ingest.audit                 # write the report
    python -m src.ingest.audit --check         # fail if any dataset is unaudited
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

from src.ingest.registry import REGISTRY, Availability, Redistribution
from src.utils.config import ROOT

REPORT = ROOT / "reports" / "license_audit.md"

# What each dataset is allowed to contribute to a published artifact.
PUBLISHABLE = {
    Redistribution.YES: "raw files, derived data, metrics, models",
    Redistribution.ATTRIBUTION: "raw files with attribution, derived data, metrics, models",
    Redistribution.NO: "metrics and models only - raw files must not leave this machine",
    Redistribution.UNKNOWN: "metrics and models only - treated as NO until resolved",
}


def rows() -> list[dict]:
    out = []
    for ds in REGISTRY.values():
        out.append(
            {
                "slug": ds.slug,
                "name": ds.name,
                "license": ds.license,
                "availability": ds.availability.value,
                "redistribution": ds.redistribution.value,
                "publishable": PUBLISHABLE[ds.redistribution],
                "present": ds.present,
                "phases": ", ".join(ds.phases),
                "url": ds.url,
            }
        )
    return sorted(out, key=lambda r: r["slug"])


def unresolved() -> list[str]:
    """Datasets that are present locally but whose redistribution status is unknown."""
    return [
        ds.slug
        for ds in REGISTRY.values()
        if ds.present and ds.redistribution is Redistribution.UNKNOWN
    ]


def write_report() -> Path:
    data = rows()
    present = [r for r in data if r["present"]]
    lines: list[str] = []
    add = lines.append

    add("# License and Availability Audit")
    add("")
    add(f"Phase 1.1.6. Generated by `python -m src.ingest.audit` on {date.today().isoformat()}.")
    add("")
    add(f"**{len(present)} of {len(data)} registered sources are present locally.**")
    add("")

    add("## Summary")
    add("")
    add("| Dataset | License | Availability | Redistribution | Present |")
    add("| :--- | :--- | :--- | :--- | :---: |")
    for r in data:
        add(
            f"| [{r['name']}]({r['url']}) | {r['license']} | {r['availability']} | "
            f"{r['redistribution']} | {'yes' if r['present'] else 'no'} |"
        )
    add("")

    add("## What may be published from each source")
    add("")
    add("| Dataset | May contribute to a published artifact |")
    add("| :--- | :--- |")
    for r in data:
        add(f"| {r['name']} | {r['publishable']} |")
    add("")

    add("## Rules this audit enforces")
    add("")
    add("1. **Unknown means no.** A source with an undeclared license is treated as")
    add("   non-redistributable until its author confirms otherwise.")
    add("2. **Raw files never enter git.** `.gitignore` excludes `data/raw/`; the registry")
    add("   records provenance so the corpus can be rebuilt instead of shipped.")
    add("3. **Attribution flows into model cards.** Any model trained on an attribution-")
    add("   licensed source names that source in its card (Phase 0.3.2).")
    add("4. **Unavailable sources stay registered.** Dead datasets keep a record with the")
    add("   evidence of their unavailability, so a substitution is never silent.")
    add("")

    unres = unresolved()
    add("## Open items")
    add("")
    if unres:
        add("| Dataset | Action needed |")
        add("| :--- | :--- |")
        for slug in unres:
            ds = REGISTRY[slug]
            add(
                f"| {ds.name} | License undeclared at {ds.url} — contact the author to "
                "confirm terms. Until then: metrics and models only. |"
            )
    else:
        add("None: every present dataset has a resolved redistribution status.")
    add("")

    add("## Substitutions made in Phase 1.1")
    add("")
    add("| Planned source | Status | Substitute | Reason |")
    add("| :--- | :--- | :--- | :--- |")
    add(
        "| FC-A / FC-B (Bresler) | unavailable | flowchartseg | archive download link "
        "returns 404 while the landing page is live; no mirror found |"
    )
    add(
        "| Sketch2Code (Microsoft) | unavailable | SALT-NLP/Sketch2Code | hosted demo and "
        "its dataset endpoint no longer resolve |"
    )
    add(
        "| IAM (original host) | account required | Teklia/IAM-line (MIT) | canonical "
        "download is behind a registration form that cannot be scripted |"
    )
    add("")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return REPORT


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if anything is unaudited")
    ap.add_argument("--json", action="store_true", help="print the audit table as JSON")
    args = ap.parse_args(argv)

    if args.json:
        print(json.dumps(rows(), indent=2))
        return 0

    path = write_report()
    print(f"wrote {path.relative_to(ROOT)}")
    for r in rows():
        mark = "present" if r["present"] else "absent "
        print(f"  {mark}  {r['slug']:<16} {r['license'][:34]:<34} {r['redistribution']}")

    unres = unresolved()
    if unres:
        print(f"\nunresolved licenses (treated as non-redistributable): {', '.join(unres)}")
    if args.check:
        missing = [
            ds.slug
            for ds in REGISTRY.values()
            if ds.availability is Availability.OPEN and not ds.present
        ]
        if missing:
            print(f"FAIL: open datasets not downloaded: {missing}", file=sys.stderr)
            return 1
        print("\nRESULT: every open dataset is present and audited")
    return 0


if __name__ == "__main__":
    sys.exit(main())
