"""Phase 1.3.4 — class balance report.

Counts every diagram type in every split and writes `reports/class_balance.md` plus a
figure. The point is not bookkeeping: this report is where the corpus's biggest weakness
becomes impossible to ignore, so that Phase 5 chooses its metrics accordingly (macro-F1, not
accuracy) and Phase 7 knows whether it needs class weighting.

    python -m src.ingest.balance
"""

from __future__ import annotations

import argparse
import json
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from src.utils.config import ROOT  # noqa: E402

REPORT = ROOT / "reports" / "class_balance.md"
FIGURE = ROOT / "reports" / "figures" / "p1_class_balance.png"

SPLIT_ORDER = ["train", "validation", "test"]


def tables(df: pd.DataFrame) -> dict:
    by_type_split = (
        df.pivot_table(index="diagram_type", columns="split", values="id", aggfunc="count")
        .reindex(columns=SPLIT_ORDER)
        .fillna(0)
        .astype(int)
    )
    by_source_type = (
        df.pivot_table(index="source", columns="diagram_type", values="id", aggfunc="count")
        .fillna(0)
        .astype(int)
    )
    totals = by_type_split.sum(axis=1).sort_values(ascending=False)
    imbalance = float(totals.max() / max(totals.min(), 1))

    diagram_only = df[df["diagram_type"] != "text"]
    diag_totals = diagram_only["diagram_type"].value_counts()

    return {
        "by_type_split": by_type_split,
        "by_source_type": by_source_type,
        "totals": totals,
        "imbalance_ratio": imbalance,
        "diagram_totals": diag_totals,
        "n_types": int(df["diagram_type"].nunique()),
    }


def figure(t: dict) -> object:
    FIGURE.parent.mkdir(parents=True, exist_ok=True)
    by = t["by_type_split"]
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    by.plot(kind="barh", stacked=True, ax=axes[0], color=["#4C78A8", "#F58518", "#54A24B"])
    axes[0].set_title("Rows per diagram type, by split")
    axes[0].set_xlabel("rows")
    axes[0].set_ylabel("")

    diag = t["diagram_totals"]
    axes[1].barh(diag.index[::-1], diag.to_numpy()[::-1], color="#4C78A8")
    axes[1].set_xscale("log")
    axes[1].set_title("Diagram types only (log scale)")
    axes[1].set_xlabel("rows (log)")
    for i, v in enumerate(diag.to_numpy()[::-1]):
        axes[1].text(v, i, f" {v}", va="center", fontsize=9)

    fig.tight_layout()
    fig.savefig(FIGURE, dpi=130)
    plt.close(fig)
    return FIGURE


def write_report(t: dict) -> object:
    lines: list[str] = []
    add = lines.append
    add("# Class Balance")
    add("")
    add("Phase 1.3.4. Generated by `python -m src.ingest.balance`.")
    add("")
    add("![class balance](figures/p1_class_balance.png)")
    add("")
    add("## Rows per diagram type and split")
    add("")
    by = t["by_type_split"]
    add("| diagram type | " + " | ".join(SPLIT_ORDER) + " | total |")
    add("| :--- | " + " | ".join("---:" for _ in SPLIT_ORDER) + " | ---: |")
    for dtype, row in by.iterrows():
        add(
            f"| {dtype} | "
            + " | ".join(str(int(row[s])) for s in SPLIT_ORDER)
            + f" | {int(row.sum())} |"
        )
    add("")
    add("## Rows per source and diagram type")
    add("")
    bs = t["by_source_type"]
    add("| source | " + " | ".join(str(c) for c in bs.columns) + " |")
    add("| :--- | " + " | ".join("---:" for _ in bs.columns) + " |")
    for src, row in bs.iterrows():
        add(f"| {src} | " + " | ".join(str(int(v)) for v in row) + " |")
    add("")

    add("## The imbalance, stated plainly")
    add("")
    add(f"Largest class is **{t['imbalance_ratio']:.0f}x** the smallest.")
    add("")
    add("This is not a corpus of five equal diagram types. It is dominated by flowchart-like")
    add("diagrams, because that is what the public datasets contain: hdBPMN, DIDI and")
    add("flowchartseg are all flowchart-shaped, while the other four types exist only in the")
    add("curated chaos corpus at 40-60 images each.")
    add("")
    add("### What this forces downstream")
    add("")
    add("| Consequence | Where it is handled |")
    add("| :--- | :--- |")
    add(
        "| Accuracy is meaningless here - predicting `flowchart` always would score well | Phase 5.2.3 reports **macro**-F1 and per-class precision/recall |"
    )
    add("| The minority types need their own PR curves, not just a global ROC | Phase 5.2.5 |")
    add(
        "| Ensembles will ignore rare classes unless reweighted | Phase 7.1: class weights / balanced sampling |"
    )
    add(
        "| A stratified split alone cannot fix a 30:1 ratio | Phase 1.3.6 augmentation, and the synthetic generator in 1.3.7, target the minority types |"
    )
    add(
        "| Reported gains may come from the majority class alone | Phase 14.2 reports per-type metrics separately |"
    )
    add("")
    add("### Why it is not simply corrected here")
    add("")
    add("Down-sampling the majority would throw away the only large, well-annotated data the")
    add("project has - hdBPMN's edge annotations are what Phase 10 learns from. The imbalance")
    add("is therefore kept and handled at the metric and sampling level, where it stays")
    add("visible, rather than hidden by resampling the corpus.")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    while lines and not lines[-1].strip():
        lines.pop()
    with REPORT.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return REPORT


def main(argv: list[str] | None = None) -> int:
    from src.ingest.manifest import load

    ap = argparse.ArgumentParser(description=__doc__)
    ap.parse_args(argv)

    df = load()
    t = tables(df)
    fig = figure(t)
    rep = write_report(t)
    print(f"wrote {rep.relative_to(ROOT)}")
    print(f"wrote {fig.relative_to(ROOT)}")
    print(
        json.dumps(
            {
                "types": t["n_types"],
                "imbalance_ratio": round(t["imbalance_ratio"], 1),
                "totals": t["totals"].to_dict(),
            },
            indent=2,
        )
    )

    checks = {
        "report_written": rep.is_file(),
        "figure_written": fig.is_file(),
        "all_splits_have_every_type": bool((t["by_type_split"] > 0).all().all()),
    }
    for name, ok in checks.items():
        print(f"  {'PASS' if ok else 'FAIL'}  {name}")
    return 0 if all(checks.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
