"""Phase 1.2 — generate the printable drawing briefs from the collection protocol.

One sheet per diagram type under `docs/collection/`. The sheets are generated, not written by
hand, so they can never disagree with `src/ingest/collection.py` about what has to be drawn.

    .venv/Scripts/python.exe scripts/make_collection_sheets.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.ingest.collection import (  # noqa: E402
    ADVERSE_CONDITIONS,
    CONDITIONS,
    MEDIA,
    SCENARIOS,
    TARGETS,
    assignments,
)

OUT = ROOT / "docs" / "collection"

TYPE_NOTES = {
    "flowchart": (
        "Draw the way you would on a whiteboard in a meeting: do not straighten arrows, do "
        "not redraw a box because it came out crooked. **If an arrow does not quite touch a "
        "box, leave it.** That gap is the single hardest thing this project has to solve "
        "(Phase 10.1.4), and clean drawings give it nothing to learn from."
    ),
    "wireframe": (
        "Sketch the layout only — boxes, lines for text, a cross for an image. Do not write "
        "real copy; a squiggle standing in for a line of text is what a real wireframe looks "
        "like. Nesting matters more than neatness: a card inside a grid inside a page."
    ),
    "state_machine": (
        "Circles for states, double circle for accepting. Label every transition, even if the "
        "label is one letter. Include at least one self-loop where the scenario allows — "
        "self-loops are the feature that separates state machines from flowcharts in the "
        "Phase 4.1.7 connectivity features."
    ),
    "er_diagram": (
        "Rectangles for entities, ovals for attributes, diamonds for relationships. Write the "
        "cardinality (1, N, M) on the lines. Underline primary keys. Attribute-heavy diagrams "
        "are what teach the Phase 7.2 Naive Bayes prior that many labels means ER."
    ),
    "circuit": (
        "Standard symbols, drawn freehand. Close the loop. Do not use a ruler. Wires crossing "
        "without a junction dot must stay unmarked — telling a crossing from a junction is "
        "exactly what Phase 10.1.7 has to learn."
    ),
}


def sheet(dtype: str) -> str:
    scen = SCENARIOS[dtype]
    rows = [r for r in assignments() if r["diagram_type"] == dtype]
    target = TARGETS[dtype]

    lines: list[str] = []
    add = lines.append
    pretty = dtype.replace("_", " ")

    add(f"# Collection Brief — {pretty.title()}")
    add("")
    add(
        f"**Target: {target} sketches** across {len(scen)} scenarios and "
        f"{len({r['scribe_id'] for r in rows})} scribes."
    )
    add("")
    add(
        "Generated by `scripts/make_collection_sheets.py` from `src/ingest/collection.py`. "
        "Do not edit by hand."
    )
    add("")
    add("## How to draw these")
    add("")
    add(TYPE_NOTES[dtype])
    add("")
    add("## Scenarios")
    add("")
    add("| # | Scenario | What to draw | Must contain |")
    add("| :---: | :--- | :--- | :--- |")
    for i, s in enumerate(scen, 1):
        add(f"| {i} | **{s.title}** (`{s.slug}`) | {s.brief} | {', '.join(s.must_contain)} |")
    add("")
    add("## Assignment")
    add("")
    add(
        "Each row is one photograph to take. The filename encodes its own metadata, so file "
        "it exactly as shown."
    )
    add("")
    add("| # | Scribe | Scenario | Medium | Condition | File |")
    add("| ---: | :--- | :--- | :--- | :--- | :--- |")
    for r in rows:
        add(
            f"| {r['index']} | {r['scribe_id']} | {r['scenario']} | {r['medium']} | "
            f"{r['condition']} | `{r['filename']}` |"
        )
    add("")
    add("## Where it goes")
    add("")
    add("```")
    add(f"data/raw/chaos/{dtype}/<scribe_id>/<scenario>__<medium>__<condition>__<index>.jpg")
    add("```")
    add("")
    add(f"Media: {', '.join(f'`{m}`' for m in MEDIA)}")
    add("")
    add(
        f"Conditions: {', '.join(f'`{c}`' for c in CONDITIONS)} "
        f"(everything except `clean` counts as adverse)"
    )
    add("")
    add("## Checking progress")
    add("")
    add("```")
    add("python -m src.ingest.collection --progress")
    add("```")
    add("")
    add(f"This type is complete when {target} valid files sit under " f"`data/raw/chaos/{dtype}/`.")

    return "\n".join(lines) + "\n"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for dtype in SCENARIOS:
        path = OUT / f"{dtype}.md"
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(sheet(dtype))
        print(
            f"  wrote {path.relative_to(ROOT)}  ({TARGETS[dtype]} sketches, "
            f"{len(SCENARIOS[dtype])} scenarios)"
        )
    print(f"{len(SCENARIOS)} sheets, {sum(TARGETS.values())} sketches total")
    print(f"adverse conditions available: {len(ADVERSE_CONDITIONS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
