"""Phase 15 - `reports/README.md`: which command writes each report, generated rather than typed.

    python scripts/reports_index.py            # rewrite reports/README.md
    python scripts/reports_index.py --check    # non-zero if it is out of date

`reports/` holds 108 files and nothing said where any of them came from. The consequence was a
slow accumulation of artefacts with no producer and no reader: a 4.96 MB raw training log,
nineteen arms of one S5 sweep written to nineteen filenames, a 43 KB dump of edge-pair
measurements. Each was committed for a reason that was true that afternoon and unrecoverable
afterwards.

The index is derived, not maintained: every report is matched against the `src/` and `scripts/`
modules that name it, so it cannot go stale in the way a hand-written list does. A report with
**no producer** is listed as such, which is the finding rather than an omission - it means the
file is in git and nothing in the repo would regenerate it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
INDEX = REPORTS / "README.md"

#: Reports that are inputs or records rather than outputs of a module, with what they are.
#: A file here is a deliberate exception; anything else with no producer is a finding.
DECLARED: dict[str, str] = {
    "README.md": "this index",
    "phase0_environment.md": "Phase 0.1's acceptance record, written once by hand",
    "phase0_scaffolding.md": "Phase 0.2's acceptance record, written once by hand",
    "p13_edge_label_null.json": "13.x's recorded null result: reading edge labels does not move "
    "S5, and the reason is the metric rather than the module",
    "mypy_baseline.json": "`scripts/typecheck.py`'s ratchet",
    "arrow_m.json": "the arrow pose run's summary, extracted from its stdout capture",
}


def producers() -> dict[str, list[str]]:
    """`report name -> the modules that write it`, by searching for the filename."""
    # This file is excluded from its own search. It writes exactly one report - `README.md`, which
    # is in `DECLARED` - and every other filename in it is an example in a comment, so leaving it in
    # makes it a claimed producer of whatever it happens to discuss.
    sources = {
        path: path.read_text(encoding="utf-8", errors="ignore")
        for base in ("src", "scripts")
        for path in sorted((ROOT / base).rglob("*.py"))
        if path != Path(__file__).resolve()
    }
    found: dict[str, list[str]] = {}
    for report in sorted(REPORTS.rglob("*")):
        if report.is_dir():
            continue
        name = report.relative_to(REPORTS).as_posix()
        stem = report.name

        def module(path: Path) -> str:
            return path.relative_to(ROOT).as_posix().removesuffix(".py").replace("/", ".")

        # A module that writes `reports/drift.json` names the whole filename. That is the reliable
        # signal and it is taken first.
        named = [module(path) for path, text in sources.items() if stem in text]
        if named:
            found[name] = named
            continue

        # Only when nothing names the file: a bare-stem match, for a module that builds the path
        # from a stem and a suffix. It is a wide net - **any prose containing the word** matches -
        # and it used to run alongside the precise one rather than behind it, which is how
        # `scripts/make_app_icons.py` came to be listed as the producer of `reports/drift.json` for
        # saying that two things "cannot drift". Behind the precise match it only ever fires where
        # the alternative is "no producer", and there it is better than nothing.
        found[name] = [
            module(path)
            for path, text in sources.items()
            if report.stem in text and report.suffix in (".md", ".json")
        ]
    return found


def _cell(name: str, owners: list[str]) -> str:
    if Path(name).name in DECLARED:
        return f"_{DECLARED[Path(name).name]}_"
    if owners:
        return ", ".join(f"`{owner}`" for owner in sorted(set(owners))[:3])
    return "**nothing - no module in this repo regenerates it**"


def render() -> str:
    rows = producers()
    reports = {n: o for n, o in rows.items() if not n.startswith("figures/")}
    figures = {n: o for n, o in rows.items() if n.startswith("figures/")}
    orphans = [n for n, o in reports.items() if not o and Path(n).name not in DECLARED]

    lines = [
        "# `reports/` - what writes each file",
        "",
        "Generated by `python scripts/reports_index.py`. Do not edit by hand; `--check` fails "
        "when it is out of date, and `tests/test_task_targets.py` runs that.",
        "",
        f"**{len(reports)} reports, {len(figures)} figures. {len(orphans)} reports have no "
        "producer in `src/` or `scripts/`** - the file is in git and nothing in the repo would "
        "regenerate it. That is the finding this index exists to surface: it is what let a "
        "4.96 MB raw training log, nineteen arms of one S5 sweep and a 43 KB edge-pair dump "
        "accumulate, each committed for a reason that was true that afternoon.",
        "",
        "| Report | Written by |",
        "| :--- | :--- |",
    ]
    lines += [f"| `{name}` | {_cell(name, owners)} |" for name, owners in sorted(reports.items())]
    lines += [
        "",
        "## Figures",
        "",
        "Matched by stem, and incompletely: several plotting modules build the filename at "
        "runtime, so a blank here is a limit of the matching rather than a missing producer.",
        "",
        "| Figure | Written by |",
        "| :--- | :--- |",
    ]
    lines += [f"| `{name}` | {_cell(name, owners)} |" for name, owners in sorted(figures.items())]
    lines.append("")
    return chr(10).join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the index is out of date")
    args = ap.parse_args(argv)

    fresh = render()
    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
        if current != fresh:
            print(
                "reports/README.md is out of date; run python scripts/reports_index.py",
                file=sys.stderr,
            )
            return 1
        print(f"reports/README.md is current ({len(list(REPORTS.rglob('*')))} entries)")
        return 0

    INDEX.write_text(fresh, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
